"""
idiom_database.py
=================
Shared idiom database used by both the Streamlit app and training pipeline.

Each entry:  idiom -> (meaning, vis_fig, vis_lit, origin)
  meaning : plain-English meaning of the idiom
  vis_fig : specific visual description of the FIGURATIVE image
  vis_lit : specific visual description of the LITERAL image
  origin  : brief etymology

These specific visual descriptions dramatically outperform generic CLIP prompts
like "an image representing the figurative meaning of X" by giving CLIP concrete
visual content to match against (e.g. "a person dying or a funeral or gravestone"
instead of "an image representing the figurative meaning of 'kick the bucket'").
"""

IDIOM_DB = {
    "couch potato":         ("a lazy person who spends all day sitting watching TV",
                             "a lazy person lying on a sofa watching television all day",
                             "a potato vegetable sitting on a couch or sofa",
                             "coined in 1976 by Tom Iacino; combines couch-sitting and potato passivity"),
    "kick the bucket":      ("to die",
                             "a person dying or a funeral or gravestone",
                             "a person kicking a metal bucket with their foot",
                             "originates from a method of hanging; 'bucket' referred to a beam"),
    "elbow grease":         ("hard physical effort or work",
                             "a person scrubbing or cleaning very hard with great effort",
                             "a person's elbow with grease or oil on it",
                             "metaphor: elbow movement = manual scrubbing effort"),
    "night owl":            ("a person who stays up very late at night",
                             "a person awake and active late at night under the moon",
                             "an owl bird sitting on a branch at night",
                             "owls are nocturnal; associated with alertness at night"),
    "bite the bullet":      ("to endure pain or difficulty bravely",
                             "a person bravely enduring pain or hardship with determination",
                             "a person biting a bullet or cartridge with their teeth",
                             "soldiers bit bullets during surgery before anaesthesia"),
    "black sheep":          ("the odd one out; a disgrace to the family",
                             "a person standing alone and rejected from a group",
                             "a black sheep standing among white sheep in a flock",
                             "a black sheep in a flock was considered less valuable"),
    "break a leg":          ("good luck, especially before a performance",
                             "a performer on stage receiving applause and success",
                             "a person breaking their leg or a broken leg",
                             "theatre superstition: wishing bad luck brings good luck"),
    "cold turkey":          ("sudden and complete withdrawal from an addiction",
                             "a person suffering withdrawal symptoms looking pale and shaking",
                             "a cold uncooked turkey on a plate",
                             "resembles pale, cold skin of someone withdrawing"),
    "raining cats and dogs":("raining extremely heavily",
                             "a heavy downpour of rain with dark storm clouds",
                             "cats and dogs falling from the sky like rain",
                             "old Norse: cats symbolised rain, dogs symbolised wind"),
    "over the moon":        ("extremely happy and delighted",
                             "a very happy joyful person celebrating with arms raised",
                             "a person flying over or jumping over the moon in space",
                             "happiness so extreme one could float to the moon"),
    "piece of cake":        ("something very easy to do",
                             "a task being done effortlessly with ease and no difficulty",
                             "a slice of cake on a plate",
                             "eating cake requires little effort"),
    "under the weather":    ("feeling unwell or ill",
                             "a sick person lying in bed with tissues looking unwell",
                             "a person standing under dark stormy weather clouds",
                             "sailors went below deck when feeling sick in bad weather"),
    "spill the beans":      ("to accidentally reveal secret information",
                             "a person whispering or revealing a secret to someone",
                             "a bag or bowl of beans being spilled on the floor",
                             "beans used in secret voting — spilling revealed the count"),
    "on thin ice":          ("in a risky or dangerous situation",
                             "a person in a dangerous or precarious risky situation",
                             "a person walking carefully on thin cracked ice over water",
                             "thin ice can break — danger beneath"),
    "hit the nail on the head":("to be exactly right about something",
                             "a person pointing confidently having discovered the exact truth",
                             "a hammer hitting a nail precisely on its head",
                             "precise hammer strike = accurate observation"),
    "let the cat out of the bag":("to accidentally reveal a secret",
                             "a surprised person discovering a hidden secret revealed",
                             "a cat jumping out of a bag or sack",
                             "medieval fraud: cat hidden in a bag sold as a pig"),
    "burn the midnight oil": ("to work very late into the night",
                             "a person working at a desk late at night under a lamp",
                             "an oil lamp burning at midnight",
                             "before electricity, burning oil lamps meant late work"),
    "red herring":          ("a misleading clue or distraction",
                             "a person being misled or distracted from the real issue",
                             "a red fish herring being dragged across a path",
                             "strong-smelling fish used to distract hunting dogs"),
    "beat around the bush": ("to avoid the main topic or point",
                             "a person nervously talking and avoiding saying something directly",
                             "a person walking around and beating bushes",
                             "beaters drove birds from bushes — circling before hunting"),
    "break the ice":        ("to reduce awkwardness and start conversation",
                             "people meeting and starting to talk comfortably at a social event",
                             "a ship or person breaking through ice",
                             "icebreaker ships clear paths — metaphor for social ease"),
    "wolf in sheep's clothing":("a dangerous person pretending to be harmless",
                             "a dangerous deceptive person hiding their true harmful intentions",
                             "a wolf wearing a sheep fleece costume",
                             "biblical metaphor for deception"),
    "cost an arm and a leg":("extremely expensive",
                             "a very expensive luxury item with a high price tag",
                             "a person giving away their arm and leg as payment",
                             "limbs are invaluable — losing one has a great cost"),
    "sour grapes":          ("pretending not to want what you cannot have",
                             "a jealous or bitter person pretending not to care about something they want",
                             "a person eating sour unripe grapes with a grimace",
                             "Aesop's fable: fox called grapes sour after failing to reach them"),
    "storm in a teacup":    ("a lot of fuss over something very minor",
                             "people overreacting dramatically to something very small and trivial",
                             "a storm with lightning and waves inside a tiny teacup",
                             "major agitation in a tiny vessel = overreaction"),
    "barking up the wrong tree":("to pursue the wrong course of action",
                             "a person searching in completely the wrong place for an answer",
                             "a dog barking at a tree while an animal watches from another tree",
                             "hunting dog barks at wrong tree where prey is not hiding"),
    "hit the sack":         ("to go to bed and sleep",
                             "a tired person getting into bed to sleep",
                             "a person hitting or punching a large sack or bag",
                             "old mattresses were sacks filled with material"),
    "burn bridges":         ("to permanently destroy a relationship",
                             "a person leaving angrily with no intention of returning",
                             "a wooden bridge on fire burning down over water",
                             "burning a bridge prevents retreat or return"),
    "cut corners":          ("to do something poorly to save time or money",
                             "a person doing sloppy rushed work to save effort",
                             "scissors or a tool cutting the corners off a shape",
                             "taking a shorter path skips required steps"),
    "in hot water":         ("to be in trouble or a difficult situation",
                             "a person in trouble or facing a serious problem",
                             "a person sitting uncomfortably in hot boiling water",
                             "hot water causes discomfort — metaphor for difficulty"),
    "bite off more than you can chew":("to take on more than you can handle",
                             "a person overwhelmed with too many tasks and responsibilities",
                             "a person trying to fit an enormous piece of food in their mouth",
                             "chewing too large a piece leads to choking"),
    "throw in the towel":   ("to admit defeat and give up",
                             "a person giving up and accepting defeat in a competition",
                             "a white towel being thrown into a boxing ring",
                             "boxing: a trainer throws a towel to stop the fight"),
    "once in a blue moon":  ("very rarely; almost never",
                             "a very rare unusual event happening almost never",
                             "a glowing blue moon in a dark night sky",
                             "a blue moon is rare — once per 2.7 years"),
    "straight from the horse's mouth":("information from the original reliable source",
                             "a person hearing important news directly from the source",
                             "a person looking inside a horse's open mouth",
                             "checking a horse's teeth reveals its true age"),
    "two peas in a pod":    ("two people who are very similar",
                             "two identical or very similar people standing together",
                             "two green peas sitting together inside an open pod",
                             "peas in the same pod are identical"),
    "see eye to eye":       ("to agree with someone completely",
                             "two people nodding and agreeing with each other happily",
                             "two pairs of eyes looking directly at each other at the same level",
                             "looking at eye level = equality and agreement"),
    "apples and oranges":   ("two things that are too different to be compared fairly",
                             "two people trying to compare completely different and incomparable things",
                             "a red apple and an orange placed side by side",
                             "comparing fundamentally different things is as absurd as comparing fruits"),
    "bad apple":            ("one corrupt person who spoils the entire group",
                             "a troublemaker being expelled from a team while upset teammates watch",
                             "one rotten brown apple among fresh red apples",
                             "one rotten apple rots the whole barrel"),
    "baby blues":           ("feeling of sadness or depression after giving birth",
                             "a new mother feeling sad overwhelmed and tearful after having a baby",
                             "a baby wearing or surrounded by blue coloured things",
                             "postpartum sadness; blue = low mood; common in new mothers"),
    "big cheese":           ("an important and powerful person in an organisation",
                             "a self-important powerful executive commanding authority over everyone",
                             "an enormous impressive wheel of cheese on display",
                             "Urdu 'chiz' meaning thing; misinterpreted as cheese in English"),
    "big fish":             ("an important influential person especially in a small group",
                             "a dominant influential person standing out and commanding respect in a small group",
                             "a large fish swimming among much smaller fish in a pond",
                             "a big fish in a small pond has disproportionate influence"),
    "brass ring":           ("a highly desirable prize goal or opportunity",
                             "a person reaching and striving ambitiously for a coveted prize or goal",
                             "a shiny brass metal ring held up as a prize or reward",
                             "carousel riders grabbed brass rings for a free ride; became a success metaphor"),
    "bread and butter":     ("the main reliable source of income or basic necessities of life",
                             "a person doing their core everyday essential work that pays the bills",
                             "a slice of bread being spread with butter",
                             "bread and butter are the most basic staple foods — metaphor for basics"),
    "busy bee":             ("a very industrious and hardworking person always doing things",
                             "an energetic person rushing between tasks working tirelessly all day",
                             "a bee flying busily between flowers collecting pollen",
                             "bees are famously industrious creatures always working in the hive"),
    "cold feet":            ("sudden nervousness or loss of confidence before doing something",
                             "a nervous anxious person hesitating and backing away from a commitment",
                             "a person's bare feet standing in cold snow or icy water",
                             "soldiers got cold feet literally in trenches; adopted as metaphor for cowardice"),
    "copy cat":             ("a person who imitates or copies others without originality",
                             "a person shamelessly copying everything another person does or creates",
                             "a cat perfectly mimicking and copying another cat's exact actions",
                             "cats were thought to imitate; 'copy' was added to emphasise imitation"),
    "dead wood":            ("useless unproductive people or elements in an organization",
                             "unproductive lazy employees being removed from a company",
                             "dead dry wood branches on a dead tree",
                             "dead wood in a tree contributes nothing"),
    "green light":          ("official permission or approval to proceed",
                             "a person receiving approval and permission to start a project",
                             "a green traffic light signal on a road",
                             "traffic lights: green means go — adapted to mean approval to proceed"),
    "heart of gold":        ("an extremely kind generous and caring person",
                             "a genuinely warm kind-hearted person helping others selflessly and lovingly",
                             "a golden heart shape made of shining gold",
                             "gold is precious and pure; a golden heart represents pure kindness"),
    "heart of stone":       ("a cold unfeeling person with no compassion or empathy",
                             "a cold heartless person showing no emotion or compassion whatsoever",
                             "a literal stone carved into the shape of a heart",
                             "stone is hard and cold — metaphor for someone without warm feelings"),
    "hot air":              ("empty meaningless talk with no substance or truth",
                             "a politician or person talking loudly while saying nothing of substance",
                             "hot steam or air rising from a vent or hot air balloon",
                             "inflated speech like a hot air balloon — full of air but no substance"),
    "hot potato":           ("a controversial sensitive issue that nobody wants to deal with",
                             "politicians and officials desperately passing a controversial problem to each other",
                             "a person struggling to hold a steaming hot potato that burns their hands",
                             "a hot potato burns if held too long — no one wants to handle it"),
    "ivory tower":          ("a state of privileged isolation from practical reality",
                             "an academic or intellectual isolated from real world problems in luxury",
                             "a tall elegant tower built from white ivory material",
                             "from the Bible Song of Solomon; adopted for academic detachment from reality"),
    "low-hanging fruit":    ("an easy task or goal that can be achieved with minimal effort",
                             "a person easily picking the simplest most accessible tasks first",
                             "fruit hanging low on a tree branch easy to reach and pick",
                             "fruit at the bottom is easiest to harvest; metaphor for easy wins"),
    "monkey business":      ("silly mischievous behaviour or dishonest suspicious activity",
                             "people engaged in suspicious sneaky or mischievous dishonest activity",
                             "monkeys causing chaos and mischief playing pranks in a comical scene",
                             "monkeys are associated with mischief and unpredictable playful behaviour"),
    "nest egg":             ("money saved for the future especially for retirement",
                             "a person carefully saving money for a secure comfortable future",
                             "a real egg sitting safely in a bird's nest",
                             "farmers put fake eggs in nests to encourage hens to lay more; savings metaphor"),
    "old flame":            ("a former romantic partner from the past",
                             "two former lovers unexpectedly meeting again after many years apart",
                             "an old burning candle flame or an aged fire burning low",
                             "flame = passion and romance; old flame = a past romantic relationship"),
    "open book":            ("a person who is completely honest and easy to understand",
                             "a completely transparent honest person with nothing to hide from anyone",
                             "a book lying open with all its pages and words fully visible",
                             "an open book reveals everything; no secrets are hidden"),
    "party animal":         ("a person who loves socialising and partying enthusiastically",
                             "an energetic enthusiastic person dancing and celebrating at a wild party",
                             "a wild animal dressed up or attending a party celebration",
                             "combines the social joy of a party with the wildness of an animal"),
    "pipe dream":           ("a hope or plan that is completely impossible to achieve",
                             "a person daydreaming about a completely unrealistic impossible fantasy",
                             "a person smoking a pipe while lost in an elaborate daydream",
                             "opium pipe hallucinations were vivid but unreal — metaphor for impossible fantasies"),
    "rat race":             ("the exhausting competitive struggle of modern working life",
                             "exhausted office workers competing desperately in a stressful never-ending routine",
                             "rats running frantically and competitively around a maze or race track",
                             "rats in laboratory mazes run endlessly without reward — metaphor for futile competition"),
    "red flag":             ("a warning sign that something is wrong or dangerous",
                             "a person noticing a serious warning sign that something is very wrong",
                             "a bright red flag being waved or raised as a signal",
                             "red flags historically warned of danger; now used for warning signs in relationships"),
    "silver bullet":        ("a simple magical solution to a complex problem",
                             "a single perfect solution that easily solves a difficult problem",
                             "a silver-coloured bullet or ammunition",
                             "werewolves killed by silver bullets; metaphor for perfect fix"),
    "snake in the grass":   ("a treacherous person who hides their true dangerous intentions",
                             "a smiling friendly person secretly plotting betrayal against their trusting friend",
                             "a dangerous snake hidden and camouflaged in tall grass",
                             "Virgil's Aeneid: a snake lurking in grass strikes unexpectedly"),
    "swan song":            ("a final performance, effort or work before ending",
                             "a performer giving their final farewell performance on stage",
                             "a white swan opening its beak and singing",
                             "swans believed to sing beautifully just before dying"),
    "top dog":              ("the most powerful or dominant person in a group",
                             "a confident dominant leader commanding authority and respect from everyone",
                             "a dog standing proudly above other dogs asserting dominance",
                             "in dogfighting the winning dog was on top; adapted to mean leader"),
    "trojan horse":         ("a deceptive strategy that appears helpful but causes harm",
                             "something appearing friendly or useful that is actually a trap",
                             "a large wooden horse sculpture outside ancient Troy city walls",
                             "Greeks hid inside a wooden horse to infiltrate Troy"),
    "two-way street":       ("a situation that requires equal effort or contribution from both sides",
                             "two people in a relationship both giving and taking equally",
                             "a road with traffic flowing in both directions simultaneously",
                             "a two-way street allows movement in both directions — both parties must contribute"),
    "wet blanket":          ("a person who dampens others enthusiasm and ruins their fun",
                             "a gloomy complaining person ruining the enjoyment and mood of a happy group",
                             "a person wrapped in a soaking wet heavy blanket looking miserable",
                             "a wet blanket smothers fire; a wet blanket person smothers enthusiasm"),
    "white elephant":       ("a possession that is useless costly and difficult to get rid of",
                             "a person stuck with a large useless expensive possession they cannot get rid of",
                             "a rare albino white elephant being presented as a gift",
                             "Siamese kings gifted sacred white elephants to troublesome nobles; upkeep ruined them"),
    "zebra crossing":       ("a pedestrian crossing marked with black and white stripes",
                             "pedestrians safely crossing a road at a striped pedestrian crossing",
                             "a zebra animal standing on a road crossing",
                             "the black and white stripes resemble a zebra's markings"),
    "peas in a pod":        ("two people who are very similar or always together",
                             "two people who are identical in personality and always inseparable",
                             "two green peas sitting together inside an open pea pod",
                             "peas in the same pod are indistinguishable from each other"),
    "snail mail":           ("traditional slow postal mail as opposed to email",
                             "a slow postal worker delivering letters very slowly compared to email",
                             "a snail carrying a letter or envelope on its shell",
                             "contrasts the slowness of a snail with the speed of email"),
    "watering hole":        ("a bar pub or place where people regularly gather to drink",
                             "friends gathering and drinking together at a busy local pub or bar",
                             "wild animals gathering at a waterhole in the savanna to drink",
                             "animals gather at watering holes to drink — metaphor for social drinking spots"),
    "guinea pig":           ("a person used as a test subject for an experiment",
                             "a person being tested or experimented on in a laboratory",
                             "a guinea pig animal in a laboratory or cage",
                             "guinea pigs were used in lab experiments"),
    "ghost town":           ("a once-busy place that is now completely empty and abandoned",
                             "an empty abandoned town with deserted streets and boarded-up buildings",
                             "a town full of ghosts or a spooky haunted abandoned settlement",
                             "towns deserted after mining booms ended; became eerie ghost-like places"),
    "white whale":          ("an obsessive unattainable goal that consumes someone",
                             "a person obsessively and desperately chasing an impossible dream",
                             "a large white sperm whale swimming in the ocean",
                             "from Moby Dick: Captain Ahab's obsessive pursuit"),
    "act of god":           ("an uncontrollable natural disaster or event",
                             "a massive storm flood earthquake or natural disaster destroying everything",
                             "a deity or divine figure performing a miraculous act from the sky",
                             "legal term for catastrophic events beyond human control"),
    "smoking gun":          ("clear and undeniable proof of guilt or wrongdoing",
                             "a detective holding up undeniable evidence that proves someone's guilt",
                             "a gun with smoke still rising from its barrel after being fired",
                             "a recently fired gun proves someone just shot it — irrefutable evidence"),
    "small fry":            ("an unimportant or insignificant person",
                             "a person being treated as unimportant minor and insignificant",
                             "small fish frying in a pan",
                             "small fry = juvenile fish; metaphor for unimportance"),
    "big gun":              ("an important powerful influential person",
                             "a powerful influential important person commanding authority",
                             "a large heavy artillery cannon or big gun weapon",
                             "big guns in battle have the most firepower — metaphor for power"),
    "dark horse":           ("an unknown competitor who unexpectedly wins or succeeds",
                             "an unknown outsider candidate surprising everyone by winning",
                             "a dark-coloured horse running in a race",
                             "an unknown horse in a race that nobody expected to win"),
    "loose cannon":         ("an unpredictable person who may cause unintentional damage",
                             "a reckless unpredictable person causing chaos through careless actions",
                             "a large ship cannon rolling freely and uncontrolled on a deck",
                             "an unsecured cannon on a ship deck was extremely dangerous"),
    "sit on the fence":     ("to remain neutral and avoid committing to a side",
                             "a person unable to decide staying neutral between two opposing sides",
                             "a person literally sitting on top of a wooden fence",
                             "sitting on a fence = being between two sides without committing"),
    "spanner in the works": ("something that disrupts or spoils a plan",
                             "a person or event disrupting and sabotaging a smooth running plan",
                             "a metal spanner wrench thrown into machine gears",
                             "throwing a tool into machinery stops it — metaphor for disruption"),
    "the last straw":       ("the final problem that makes a situation intolerable",
                             "a person finally reaching their breaking point after too many problems",
                             "a single straw being placed on a pile of straw breaking a camel's back",
                             "the straw that broke the camel's back — one too many burdens"),
    "turn a blind eye":     ("to deliberately ignore something wrong",
                             "a person pretending not to see obvious wrongdoing happening nearby",
                             "a person covering or closing one eye deliberately",
                             "attributed to Admiral Nelson who ignored a battle signal at Copenhagen"),
    "under the table":      ("secretly and illegally especially involving money",
                             "a person secretly passing money illegally in a shady deal",
                             "money being passed underneath a table out of sight",
                             "hidden dealings below the table avoid official scrutiny"),
    "yellow streak":        ("cowardice; tendency to be afraid",
                             "a cowardly frightened person running away from danger",
                             "a yellow stripe or streak painted down someone's back",
                             "a yellow streak down the back symbolises cowardice"),
    "throw cold water":     ("to discourage or dampen enthusiasm for something",
                             "a person discouraging and dampening someone else's excitement and plans",
                             "a person throwing a bucket of cold water on someone",
                             "cold water literally shocks and dampens — metaphor for discouragement"),
    "have the upper hand":  ("to be in a position of advantage or control",
                             "a person in a dominant controlling advantageous position over others",
                             "a hand placed on top of other hands in a stacking gesture",
                             "the top hand in a grip has more control — metaphor for advantage"),
    "put your foot in it":  ("to say something embarrassing or tactless by mistake",
                             "a person looking embarrassed after saying something very awkward",
                             "a person accidentally stepping their foot into something messy",
                             "stepping into something unpleasant — metaphor for social blunders"),
    "add fuel to the fire": ("to make a bad situation worse",
                             "a person making an already bad argument or conflict much worse",
                             "a person pouring petrol or fuel onto a burning fire",
                             "adding fuel makes fire bigger — metaphor for escalating problems"),
    "all bark no bite":     ("someone who makes threats but doesn't follow through",
                             "a person who makes loud aggressive threats but is actually harmless",
                             "a dog barking loudly but cowering and not attacking",
                             "a barking dog that does not actually bite — all threat, no action"),
    "at the drop of a hat": ("immediately and without hesitation",
                             "a person acting instantly and immediately without any hesitation",
                             "a hat being dropped quickly to the ground",
                             "dropping a hat was a signal to start — instantly"),
    "back to the drawing board":("to start planning something over from the beginning",
                             "a person frustrated starting a project completely from scratch again",
                             "an architect or designer returning to their empty drawing board",
                             "when a design fails you return to the drawing board to start over"),
    "barking mad":          ("completely crazy or insane",
                             "a wildly crazy person behaving completely out of control and irrational",
                             "a dog barking frantically and uncontrollably at everything",
                             "barking like a mad dog — extreme erratic behaviour"),
    "bite the hand that feeds you":("to act ungratefully toward someone who helps you",
                             "an ungrateful person turning against the person who helped them most",
                             "a dog biting the hand of the person feeding it",
                             "biting the one who feeds you is the ultimate ingratitude"),
    "blow your own trumpet": ("to boast or brag about your own achievements",
                             "a person loudly boasting and bragging about their own accomplishments",
                             "a person playing and blowing a brass trumpet instrument",
                             "fanfares announced important arrivals — blowing your own = self-promotion"),
    "bolt from the blue":   ("a sudden unexpected shock or surprise",
                             "a person completely shocked by a sudden unexpected event",
                             "a bolt of lightning striking suddenly from a clear blue sky",
                             "lightning from a cloudless sky is completely unexpected"),
    "bull in a china shop": ("a clumsy person who causes damage in a delicate situation",
                             "a clumsy person carelessly causing damage in a delicate situation",
                             "a large bull rampaging through a fragile china and porcelain shop",
                             "a bull's size and horns would destroy delicate crockery"),
    "burn your boats":      ("to take an irreversible action that prevents going back",
                             "a person making an irreversible commitment with no way to go back",
                             "wooden boats being set on fire and burning on water",
                             "ancient generals burned ships to prevent retreat — full commitment"),
    "by the skin of your teeth":("to barely succeed or escape by the smallest margin",
                             "a person barely escaping disaster by the smallest possible margin",
                             "a person's teeth with the thinnest layer of skin barely covering them",
                             "teeth have no skin — the narrowest possible margin of escape"),
    "can of worms":         ("a situation that creates more problems when opened",
                             "a person opening a problem that makes everything much more complicated",
                             "a tin can being opened to reveal many wriggling worms inside",
                             "once opened, worms escape everywhere — problems multiply"),
    "caught red-handed":    ("discovered in the act of doing something wrong",
                             "a person caught in the act of committing a crime with evidence",
                             "a person with blood or red paint caught visibly on their hands",
                             "having blood on hands from a crime — caught at the moment of wrongdoing"),
    "change your tune":     ("to change your opinion or attitude completely",
                             "a person completely reversing their previous opinion or position",
                             "a musician changing the song they are playing on an instrument",
                             "changing the melody you sing — metaphor for changing your position"),
    "chip on your shoulder":("holding a grudge or feeling resentful about past unfairness",
                             "an angry resentful person holding a permanent grudge from the past",
                             "a person carrying a large wooden chip balanced on their shoulder",
                             "daring someone to knock a chip off your shoulder invited a fight"),
    "come out of your shell":("to become more confident and less shy",
                             "a shy person gradually becoming more confident and outgoing",
                             "a snail or tortoise emerging slowly from its protective shell",
                             "shells protect creatures — coming out means becoming open and social"),
    "cry wolf":             ("to raise false alarms repeatedly",
                             "a person raising false alarms so often that nobody believes them",
                             "a young shepherd boy crying out and pointing at a wolf",
                             "Aesop's fable: the boy who cried wolf was ignored when the wolf came"),
    "dead ringer":          ("a person or thing that looks exactly like another",
                             "two people who look absolutely identical and could be mistaken for each other",
                             "a bell ringer at a funeral tolling a death knell",
                             "ring = exact duplicate; a dead ringer is a perfect double"),
    "don't rock the boat":  ("to avoid causing trouble or disturbing the status quo",
                             "a person carefully avoiding any action that might upset the current situation",
                             "a person rocking a small boat dangerously on water",
                             "rocking a boat risks capsizing — metaphor for disrupting stability"),
    "every cloud has a silver lining":("every bad situation has a positive aspect",
                             "a person finding hope and positivity in a difficult situation",
                             "dark storm clouds with bright silver edges glowing in sunlight",
                             "dark clouds have bright silver edges — hope in every difficulty"),
    "face the music":       ("to accept the unpleasant consequences of your actions",
                             "a person bravely accepting punishment or the consequences of mistakes",
                             "a performer nervously facing an orchestra or an audience",
                             "actors had to face the orchestra pit — confronting the truth"),
    "feather in your cap":  ("an achievement you can be proud of",
                             "a person proudly displaying an impressive achievement or accomplishment",
                             "a person wearing a hat with a decorative feather in it",
                             "Native American and medieval warriors wore feathers for victories"),
    "feel under the gun":   ("to feel under pressure to act quickly",
                             "a person feeling intense pressure and stress to complete something urgently",
                             "a person with a gun pointed at them under threat",
                             "the immediate threat of a weapon creates intense urgency"),
    "fifth wheel":          ("an unnecessary or unwanted person in a group",
                             "a person who feels completely unnecessary and unwanted in a group",
                             "a fifth wheel attached uselessly to a four-wheeled vehicle",
                             "a vehicle only needs four wheels — the fifth is redundant and useless"),
    "fish out of water":    ("a person in an unfamiliar or uncomfortable situation",
                             "a person looking completely lost and out of place in an unfamiliar situation",
                             "a fish lying helplessly out of water on dry land",
                             "a fish cannot survive out of water — extreme discomfort in wrong environment"),
    "fit as a fiddle":      ("in excellent health and physical condition",
                             "a very healthy fit energetic person in peak physical condition",
                             "a violin fiddle instrument in perfect working condition",
                             "fiddle = violin; fit = in good working order"),
    "get out of hand":      ("to become uncontrollable",
                             "a chaotic situation that has completely spiralled out of control",
                             "a person losing grip as something slips from their hand",
                             "losing physical grip — metaphor for losing control of a situation"),
    "get the ball rolling": ("to start a process or activity",
                             "a person enthusiastically starting and initiating a new project or activity",
                             "a large ball being pushed and beginning to roll forward",
                             "starting a ball rolling keeps it in motion — beginning a process"),
    "give the cold shoulder":("to deliberately ignore or snub someone",
                             "a person pointedly ignoring and turning their back on someone",
                             "a person turning away showing only their cold shoulder",
                             "presenting a cold shoulder = deliberate unfriendly dismissal"),
    "go back to square one":("to start all over again from the beginning",
                             "a frustrated person starting an entire project completely over from scratch",
                             "a board game with players returning to the first starting square",
                             "board games: landing on a penalty square sends you back to start"),
    "golden opportunity":   ("a very favourable and rare chance that should not be missed",
                             "a person seizing a rare wonderful once-in-a-lifetime opportunity",
                             "a glowing golden door or treasure chest representing opportunity",
                             "gold represents rarity and value — a golden chance is precious"),
    "grasp the nettle":     ("to tackle a difficult problem boldly",
                             "a person boldly tackling a difficult challenging problem head-on",
                             "a person grabbing and grasping a stinging nettle plant",
                             "gripping a nettle firmly stings less than touching it lightly"),
    "have a field day":     ("to enjoy a great opportunity for activity or criticism",
                             "a person thoroughly enjoying themselves exploiting a great opportunity",
                             "children playing and running freely on a large open field",
                             "field days were school outdoor activity days full of fun"),
    "have your cake and eat it":("to want contradictory things at the same time",
                             "a person greedily wanting two incompatible things simultaneously",
                             "a person eating a cake while trying to keep it whole at the same time",
                             "you cannot both possess and consume a cake — contradictory desires"),
    "hit the ground running":("to start something with great energy and enthusiasm",
                             "a person starting a new job or project with immediate full energy",
                             "a person hitting the ground running at full sprint from the start",
                             "paratroopers hit the ground running to avoid enemy fire"),
    "in the same boat":     ("in the same difficult situation as others",
                             "a group of people all facing exactly the same difficult problem together",
                             "several people crowded together in a small boat on water",
                             "people sharing a boat share the same fate — common predicament"),
    "jump on the bandwagon":("to join a popular trend or movement for personal gain",
                             "a person hastily joining a popular trend because everyone else is doing it",
                             "a person jumping onto a moving carnival bandwagon parade float",
                             "politicians joined popular bandwagons in parades for votes"),
    "keep a low profile":   ("to avoid attention or stay out of the spotlight",
                             "a person deliberately staying quiet and out of public attention",
                             "a person crouching low and trying to be invisible and unnoticed",
                             "low profile = minimal visibility; staying under the radar"),
    "kick the can down the road":("to postpone dealing with a problem",
                             "a person repeatedly delaying and avoiding dealing with an important problem",
                             "a person kicking a tin can forward along a road",
                             "kicking a can keeps it moving without actually dealing with it"),
    "know the ropes":       ("to understand how something works through experience",
                             "an experienced expert person who knows exactly how everything works",
                             "a sailor learning and handling the many ropes on a sailing ship",
                             "sailing ships had complex rope systems sailors had to master"),
    "learn the ropes":      ("to learn the basics of a new job or activity",
                             "a new person slowly learning how to do their new job properly",
                             "a beginner sailor being taught how to handle ship ropes",
                             "new sailors had to learn which ropes controlled which sails"),
    "leave no stone unturned":("to try every possible option in a thorough search",
                             "a person searching extremely thoroughly and leaving nothing unexplored",
                             "a person lifting and turning over every stone on the ground",
                             "thorough treasure hunters turned every stone — exhaustive effort"),
    "let sleeping dogs lie":("to avoid bringing up old problems or conflicts",
                             "a person wisely choosing not to bring up past problems or conflicts",
                             "a peaceful sleeping dog lying undisturbed on the ground",
                             "disturbing a sleeping dog risks a bite — leave past issues alone"),
    "light at the end of the tunnel":("hope that a difficult situation will end",
                             "a person seeing hope and relief after a long difficult struggle",
                             "a small bright light visible at the far end of a dark tunnel",
                             "emerging from a dark tunnel into light — end of hardship"),
    "like a bull in a china shop":("behaving clumsily in a delicate situation",
                             "a clumsy person causing chaos and destruction in a delicate situation",
                             "an enormous bull rampaging and smashing through a china porcelain shop",
                             "a bull's size and power would destroy delicate crockery everywhere"),
    "make ends meet":       ("to have just enough money to cover basic expenses",
                             "a person struggling financially just barely managing to pay their bills",
                             "a person stretching money trying to make two ends of a rope meet",
                             "accounting: making the two ends of a budget balance exactly"),
    "miss the boat":        ("to miss an opportunity",
                             "a person watching helplessly as an opportunity passes them by",
                             "a person running late watching a boat depart without them",
                             "literally missing a departing boat — opportunity gone"),
    "no pain no gain":      ("you must work hard and suffer to achieve success",
                             "a person working extremely hard through pain to achieve their goal",
                             "a person exercising intensely in pain at a gym",
                             "athletic training principle: discomfort produces results"),
    "on the ball":          ("alert, competent and quick to understand",
                             "a sharp alert competent person who quickly grasps everything",
                             "a person balanced and focused on top of a ball",
                             "keeping your eye on the ball means staying focused and alert"),
    "on the fence":         ("unable to decide between two options",
                             "a person unable to commit to either side of an argument or decision",
                             "a person sitting uncertainly on top of a wooden fence",
                             "being between two sides — fence as boundary between options"),
    "on the tip of your tongue":("almost remembering something but not quite",
                             "a person struggling to recall a word or name that is almost remembered",
                             "a person pointing to the tip of their tongue trying to remember",
                             "the word feels like it's physically present on the tongue"),
    "out of the blue":      ("completely unexpectedly and without warning",
                             "a person shocked by a completely unexpected sudden event",
                             "something falling suddenly from a clear blue sky without warning",
                             "nothing in a blue sky suggests what is about to appear — pure surprise"),
    "paint the town red":   ("to go out and celebrate wildly",
                             "people celebrating enthusiastically having a wild exciting night out",
                             "a person literally painting buildings and streets bright red",
                             "possibly from a rowdy night out by the Marquess of Waterford"),
    "pass the buck":        ("to shift responsibility to someone else",
                             "a person avoiding responsibility by passing blame to someone else",
                             "a person passing a token or dollar bill to someone else",
                             "in poker a buck marker showed whose turn it was to deal"),
    "pull someone's leg":   ("to tease or joke with someone",
                             "a person laughing while playing a funny joke on a friend",
                             "a person physically pulling and tugging another person's leg",
                             "street tricksters tripped victims by pulling their legs"),
    "put your foot down":   ("to insist firmly on something",
                             "a person firmly insisting and asserting their decision with authority",
                             "a person firmly pressing their foot down on the ground",
                             "pressing foot down firmly = firm decisive action"),
    "raise the bar":        ("to set higher standards",
                             "a person setting a higher standard that others must now meet",
                             "an athlete raising a high jump bar to a greater height",
                             "high jump bar: raising it literally sets a higher standard"),
    "run out of steam":     ("to lose energy or enthusiasm and be unable to continue",
                             "a person becoming completely exhausted and losing all motivation",
                             "a steam engine running low on steam slowing to a stop",
                             "steam engines stop when they run out of steam — energy metaphor"),
    "save for a rainy day": ("to keep money or resources for a future difficult time",
                             "a person carefully saving money for a future emergency or difficult time",
                             "a person putting money away while it rains outside",
                             "rainy days are unproductive — saving for them means preparing for hardship"),
    "shoot yourself in the foot":("to do something that harms your own interests",
                             "a person accidentally sabotaging their own plans or reputation",
                             "a person accidentally shooting themselves in their own foot",
                             "literally the most self-defeating injury — hurting your own cause"),
    "show your true colours":("to reveal your real character or intentions",
                             "a person finally revealing their true deceptive character to everyone",
                             "a person removing a disguise to reveal their real colourful identity",
                             "ships used false flags — showing true colours meant revealing real allegiance"),
    "skating on thin ice":  ("taking a risky action that could lead to danger",
                             "a person taking dangerous risks that could lead to serious trouble",
                             "a person ice skating dangerously on very thin cracking ice",
                             "thin ice cracks under pressure — danger of falling through"),
    "sleep on it":          ("to delay making a decision until the next day",
                             "a person taking time to think carefully before making an important decision",
                             "a person sleeping with a thought bubble above their head",
                             "sleeping allows the subconscious to process — clearer thinking next day"),
    "smell a rat":          ("to suspect that something is wrong or dishonest",
                             "a person suspiciously sensing that something dishonest is going on",
                             "a person sniffing the air as a rat runs past suspiciously",
                             "a decomposing rat smell alerts danger — detecting dishonesty"),
    "steal someone's thunder":("to take credit or attention away from someone else",
                             "a person upstaging and taking all the attention away from someone",
                             "a person dramatically stealing a lightning bolt or thunder from another",
                             "playwright John Dennis had his thunder effect stolen — coined the phrase"),
    "stir up a hornet's nest":("to cause trouble by interfering with something",
                             "a person causing a massive angry reaction by interfering carelessly",
                             "a person poking at an active angry hornet's nest",
                             "disturbing hornets provokes a dangerous swarm — stirring trouble"),
    "straight from the shoulder":("directly and honestly without holding back",
                             "a person speaking very directly and honestly without any hesitation",
                             "a boxer throwing a direct powerful straight punch from the shoulder",
                             "boxing: a straight punch is the most direct and powerful — unfiltered honesty"),
    "take the bull by the horns":("to confront a difficult problem directly and bravely",
                             "a person bravely confronting a difficult challenge directly",
                             "a person grabbing and holding a charging bull by its horns",
                             "rodeo skill of grabbing bull horns — facing danger head-on"),
    "take with a pinch of salt":("to be sceptical about the truth of something",
                             "a person listening sceptically and doubtfully to an unlikely claim",
                             "a person adding a tiny pinch of salt to food",
                             "Roman general Pompey took an antidote with salt — reducing impact"),
    "talk nineteen to the dozen":("to talk very quickly without stopping",
                             "a person talking extremely rapidly and non-stop without pausing",
                             "a person's mouth moving incredibly fast producing many words",
                             "Cornish mine pumps: 19 gallons per 12 units — exceptional output rate"),
    "the apple of your eye":("a person who is cherished above all others",
                             "a person looking adoringly at their most treasured and beloved person",
                             "a shining apple placed lovingly in the centre of an eye",
                             "the pupil was called the apple of the eye — most precious part"),
    "the ball is in your court":("it is now your responsibility to take action",
                             "a person waiting expectantly for another person to make the next move",
                             "a tennis or squash ball bouncing into the opponent's court",
                             "tennis: when the ball is in your court it is your turn to play"),
    "the best of both worlds":("to enjoy the advantages of two different situations",
                             "a person happily enjoying the best advantages of two completely different things",
                             "a person standing between two contrasting worlds enjoying both",
                             "having everything from both sides — maximum advantage"),
    "the bottom line":      ("the most important fact or the final result",
                             "a person cutting through everything to state the most essential point",
                             "the final bottom line of numbers on a financial accounting statement",
                             "accounting: the bottom line is the final profit or loss figure"),
    "the tip of the iceberg":("a small visible part of a much larger hidden problem",
                             "a person realising that a small visible problem hides a massive hidden one",
                             "the small tip of a massive iceberg visible above the ocean surface",
                             "90% of an iceberg is submerged — most of the problem is hidden"),
    "through the grapevine":("to hear news informally through gossip",
                             "a person whispering gossip passing information secretly through a chain",
                             "a person sending a message through grapevine plants",
                             "Civil War telegraph lines resembled grapevines — informal communication"),
    "throw the book at":    ("to punish someone as severely as possible",
                             "a judge sentencing a criminal to the harshest possible punishment",
                             "a judge or person throwing a large law book at someone",
                             "the book of laws used to maximum extent — maximum penalty"),
    "tighten your belt":    ("to spend less money due to reduced income",
                             "a person making careful cutbacks and spending much less money",
                             "a person pulling their belt tighter around a slimmer waist",
                             "less food = thinner waist = tighter belt — poverty metaphor"),
    "tip the scales":       ("to change the balance of a situation decisively",
                             "a person or factor decisively changing the balance of a situation",
                             "a person placing a weight on scales to make one side tip down",
                             "adding weight to scales changes the balance — decisive influence"),
    "walking on eggshells": ("to be very careful not to upset someone",
                             "a person being extremely careful and cautious not to upset someone sensitive",
                             "a person nervously walking very carefully on fragile eggshells",
                             "eggshells crack with the slightest pressure — extreme delicacy required"),
    "weather the storm":    ("to survive a difficult period",
                             "a person bravely enduring and surviving a very difficult situation",
                             "a ship or person struggling through a powerful storm at sea",
                             "navigating through a storm and surviving — enduring hardship"),
}


def lookup_idiom(sentence):
    """Find the best matching idiom in a sentence. Returns (idiom, meaning, origin, vis_fig, vis_lit)."""
    s = sentence.lower()
    best, best_len = None, 0
    for idiom in IDIOM_DB:
        if idiom in s and len(idiom) > best_len:
            best, best_len = idiom, len(idiom)
    if best:
        entry = IDIOM_DB[best]
        meaning, vis_fig, vis_lit, origin = entry
        return best, meaning, origin, vis_fig, vis_lit
    return None, None, None, None, None


def get_visual_prompts(idiom):
    """
    Returns (vis_fig, vis_lit) for a known idiom, or (None, None) if not in DB.
    vis_fig: specific visual description of the figurative image
    vis_lit: specific visual description of the literal image
    """
    if idiom and idiom.lower() in IDIOM_DB:
        entry = IDIOM_DB[idiom.lower()]
        return entry[1], entry[2]  # vis_fig, vis_lit
    return None, None
